### ISSUE TITLE
http proxy

### ISSUE THREAD

**Issue by eljeffeg** [CybercentreCanada/assemblyline-base#1042]
We use an http proxy in our environment and faced some challenges getting things working correctly.  Thank you @cccs-rs  for working through them with me. This is to document using a proxy in assemblyline.

The containers that appear to need the proxy are `updater` and the `update_server` instances for things such as pulling down yara, sigma, and suricata rules.  

1. For service updater instances, add the proxy to the proxy field in the UI in the `Update sources` section or the service's container configuration.
2. The proxy information fort the core updater container can be placed in the `config.yml`. It is import that some services (redis,minio,elasticsearch) be defined in the updater with `no proxy`.

In the `config.yml`, I've set these for the `updater` container.
```
  updater:
    environment:
        - name: http_proxy
          value: 'http://{host}:{port}'
        - name: https_proxy
          value: 'http://{host}:{port}'
        - name: no_proxy
          value: 'localhost,127.0.0.1,redis,minio,service-server,elasticsearch,{localdomain}'
```
